export const GET_CITY_DATA = 'GET_CITY_DATA';
export const GET_CITY_DATA_ERROR = 'GET_CITY_DATA_ERROR';
export const GET_CITY_DATA_RECEIVED = 'GET_CITY_DATA_RECEIVED';
export const CITY_SELECTED = 'CITY_SELECTED';

