"use strict"

export const LOAD_SHOWS_REQUEST = 'LOAD_SHOWS_REQUEST';
export const RECEIVE_SHOWS_REQUEST = 'RECEIVE_SHOWS_REQUEST';


export const LOAD_EMOTION_REQUEST = 'LOAD_EMOTION_REQUEST';
export const RECEIVE_EMOTION_REQUEST = 'RECEIVE_EMOTION_REQUEST';
